//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_CW_7417.Client.SwipesCollectionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Terminal", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_7417.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Terminal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CP_CW_7417.Client.SwipesCollectionService.SwipeStatus SwipeStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CP_CW_7417.Client.SwipesCollectionService.SwipeStatus SwipeStatus {
            get {
                return this.SwipeStatusField;
            }
            set {
                if ((this.SwipeStatusField.Equals(value) != true)) {
                    this.SwipeStatusField = value;
                    this.RaisePropertyChanged("SwipeStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SwipeStatus", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_7417.BLL.Enums")]
    public enum SwipeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProcess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Swipe", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_7417.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Swipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SwipeDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SwipeDirectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SwipeDateTime {
            get {
                return this.SwipeDateTimeField;
            }
            set {
                if ((this.SwipeDateTimeField.Equals(value) != true)) {
                    this.SwipeDateTimeField = value;
                    this.RaisePropertyChanged("SwipeDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwipeDirection {
            get {
                return this.SwipeDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SwipeDirectionField, value) != true)) {
                    this.SwipeDirectionField = value;
                    this.RaisePropertyChanged("SwipeDirection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SwipesCollectionService.ISwipesCollectionService")]
    public interface ISwipesCollectionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/StartCollectingSwipes", ReplyAction="http://tempuri.org/ISwipesCollectionService/StartCollectingSwipesResponse")]
        void StartCollectingSwipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/StartCollectingSwipes", ReplyAction="http://tempuri.org/ISwipesCollectionService/StartCollectingSwipesResponse")]
        System.Threading.Tasks.Task StartCollectingSwipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/GetStatus", ReplyAction="http://tempuri.org/ISwipesCollectionService/GetStatusResponse")]
        CP_CW_7417.Client.SwipesCollectionService.Terminal[] GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/GetStatus", ReplyAction="http://tempuri.org/ISwipesCollectionService/GetStatusResponse")]
        System.Threading.Tasks.Task<CP_CW_7417.Client.SwipesCollectionService.Terminal[]> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/GetAllSwipes", ReplyAction="http://tempuri.org/ISwipesCollectionService/GetAllSwipesResponse")]
        CP_CW_7417.Client.SwipesCollectionService.Swipe[] GetAllSwipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipesCollectionService/GetAllSwipes", ReplyAction="http://tempuri.org/ISwipesCollectionService/GetAllSwipesResponse")]
        System.Threading.Tasks.Task<CP_CW_7417.Client.SwipesCollectionService.Swipe[]> GetAllSwipesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISwipesCollectionServiceChannel : CP_CW_7417.Client.SwipesCollectionService.ISwipesCollectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SwipesCollectionServiceClient : System.ServiceModel.ClientBase<CP_CW_7417.Client.SwipesCollectionService.ISwipesCollectionService>, CP_CW_7417.Client.SwipesCollectionService.ISwipesCollectionService {
        
        public SwipesCollectionServiceClient() {
        }
        
        public SwipesCollectionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SwipesCollectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwipesCollectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwipesCollectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartCollectingSwipes() {
            base.Channel.StartCollectingSwipes();
        }
        
        public System.Threading.Tasks.Task StartCollectingSwipesAsync() {
            return base.Channel.StartCollectingSwipesAsync();
        }
        
        public CP_CW_7417.Client.SwipesCollectionService.Terminal[] GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<CP_CW_7417.Client.SwipesCollectionService.Terminal[]> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        public CP_CW_7417.Client.SwipesCollectionService.Swipe[] GetAllSwipes() {
            return base.Channel.GetAllSwipes();
        }
        
        public System.Threading.Tasks.Task<CP_CW_7417.Client.SwipesCollectionService.Swipe[]> GetAllSwipesAsync() {
            return base.Channel.GetAllSwipesAsync();
        }
    }
}
